In [5]:
# start 22.10.2017 18:54
# end   22.10.2017 19:40
# total: 46 min

In [6]:
import random
import numpy as np
import math

In [16]:
def genData(n,l):
    rotL = lambda x:x[1:] + [x[0]]
    
    rand = lambda x:map(lambda y:random.choice([0.0,1.0]) ,range(l))
    
    x = map(rand, range(n))
    y = map(rotL, x)
    
    x = map(np.array,x)
    y = map(np.array,y)
    
    return zip(x,y)

In [105]:
def sigmoid(x):
    return 1.0/(1.0 + math.exp(-x))

class NN:
    def __init__(self, ll, lr = 0.05):
        self.ll = ll
        self.lr = lr
        
        self.w, self.b = self.genWB()
        
    def genWB(self):
        w = [np.random.randn(nin, nout) for (nin, nout) in zip(self.ll[:-1], self.ll[1:])]
        b = [np.random.randn(nout)      for nout        in self.ll[1:]]
        
        return w,b
    
    def ff(self,x):
        f = np.vectorize(sigmoid)
        
        w = self.w
        b = self.b
        
        v  = [None for l in self.ll]
        vf = [None for l in self.ll]
        
        v[0]  = x
        vf[0] = f(x)
        
        for i in range(len(w)):
            v[i+1]  = np.dot(np.transpose(w[i]), v[i]) + b[i]
            vf[i+1] = f(v[i+1])
            
        
            
        return v,vf
    
    def fb(self,v,vf,y):
        w = self.w
        b = self.b
        
        f  = np.vectorize(sigmoid)
        df = lambda z: (1 - f(z)) * f(z)
        
        g  = [None for wi in w]
        gw = [None for wi in w]
        gb = [None for wi in w]
        
        g[-1] = (vf[-1] - y)*df(v[-1])
        for i in range(len(w)-2,-1,-1):
            g[i]  = np.multiply(np.dot(w[i+1],g[i+1]), df(v[i+1]))
        
        for i in range(len(w)-1,-1,-1):
            gw[i] = np.transpose(np.outer(g[i], v[i]))
            #print gw[i]
            
        return gw, g
    
    def trainStep(self,x,y):
        v, vf = self.ff(x)
        gw,gb = self.fb(v,vf,y)
        #print gw
        #print np.multiply(gw,self.lr)
        self.w = self.w - np.multiply(gw,self.lr)
        #print self.w
        #print ""
        self.b = self.b - np.multiply(gb,self.lr)
        
        v2, vf2 = self.ff(x)
        
        [e1,e2] = self.err(vf[-1],y), self.err(vf2[-1],y)
        return [e1, e2]
        
    def err(self, out, y):        
        return math.sqrt(sum((out - y) ** 2.0))
    
    def test(self,dat):
        for (x,y) in dat:
            v,vf = self.ff(x)
            e    = self.err(vf[-1],y)
            print "x = {}, y = {}, out = {}, e = {}".format(x,y,vf[-1],e)
        
                    
dat = genData(40000,3)        
layers = [[3,5,3], [3,4,5,3]]
for ll in layers:
    print "ll = {}".format(ll)
    nn = NN(ll, 0.05)
    for (x,y) in dat:
        #print x
        #v,vf = nn.ff(x)
        #print v
        #print vf
        #nn.fb(v,vf,y)
        nn.trainStep(x,y)
        
    nn.test(dat[:10])

ll = [3, 5, 3]
x = [ 1.  1.  0.], y = [ 1.  0.  1.], out = [ 0.99240534  0.00956557  0.99041566], e = 0.0155254189266
x = [ 1.  1.  1.], y = [ 1.  1.  1.], out = [ 0.98698044  0.98509183  0.98911394], e = 0.0225891296998
x = [ 0.  1.  0.], y = [ 1.  0.  0.], out = [ 0.99388062  0.01190352  0.016234  ], e = 0.021040041681
x = [ 1.  1.  0.], y = [ 1.  0.  1.], out = [ 0.99240534  0.00956557  0.99041566], e = 0.0155254189266
x = [ 0.  0.  1.], y = [ 0.  1.  0.], out = [ 0.00782016  0.99093222  0.01638546], e = 0.0202944019159
x = [ 1.  1.  1.], y = [ 1.  1.  1.], out = [ 0.98698044  0.98509183  0.98911394], e = 0.0225891296998
x = [ 0.  1.  0.], y = [ 1.  0.  0.], out = [ 0.99388062  0.01190352  0.016234  ], e = 0.021040041681
x = [ 1.  0.  1.], y = [ 0.  1.  1.], out = [ 0.00630136  0.98871455  0.99050486], e = 0.0160382713543
x = [ 0.  0.  0.], y = [ 0.  0.  0.], out = [ 0.01340395  0.0157215   0.01859355], e = 0.0277948083741
x = [ 1.  0.  1.], y = [ 0.  1.  1.], out = [ 0.00630136  0.

In [106]:
nn.ff([0,0,0])

([[0, 0, 0],
  array([-1.65725214,  0.4778998 , -1.34683734,  0.67521731]),
  array([-4.4819339 ,  2.64348865,  0.917422  , -0.06468444,  0.02717046]),
  array([-4.42840984, -5.77726428, -4.40254171])],
 [array([ 0.5,  0.5,  0.5]),
  array([ 0.16013121,  0.61725182,  0.20638791,  0.66267042]),
  array([ 0.011185  ,  0.93360853,  0.71451653,  0.48383453,  0.5067922 ]),
  array([ 0.01179272,  0.00308761,  0.01209802])])

In [107]:
nn.w

array([ array([[ 0.97967589, -0.86919222,  0.49992538,  1.09985099],
       [-1.13356107,  0.22016501,  0.4373572 , -0.83926199],
       [-0.3431183 ,  1.49244349, -0.06090128,  0.78324412]]),
       array([[-0.32866295,  0.70310799, -0.97442744, -0.83683225,  1.32071298],
       [ 0.24751731,  0.73167319, -0.82948313,  1.0483886 ,  0.59078058],
       [ 2.70175699, -1.43323762,  0.77319265,  1.07598952, -0.03313636],
       [-0.28323829,  0.72290797,  0.17833991, -0.33179907,  1.85285582]]),
       array([[ 1.4140245 ,  2.16626985,  0.16676872],
       [-0.16729143,  1.61326412, -2.26314527],
       [ 2.93240542, -0.9235387 ,  3.3291025 ],
       [ 2.06456757,  2.52825647,  0.0607288 ],
       [-0.41093381,  1.49935759,  3.12760522]])], dtype=object)